/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Alejandro Serrano Loredo
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    Gestionar_SAX gesSAX = new Gestionar_SAX();
    Gestionar_XPath gesXPath = new Gestionar_XPath();
    Gestionar_JAXB gesJAXB = new Gestionar_JAXB();
    Gestionar_DOM gesDOM = new Gestionar_DOM();

    private File ficheroXML = null;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupConsulta = new javax.swing.ButtonGroup();
        buttonGroupCambios = new javax.swing.ButtonGroup();
        jButtonConectarSAX = new javax.swing.JButton();
        jLabelMensajeConexion = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        home = new javax.swing.JPanel();
        jButtonMostrarSAX = new javax.swing.JButton();
        jLabelMensajeSAX = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSalidaSAX = new javax.swing.JTextArea();
        revisar = new javax.swing.JPanel();
        jButtonMostrarPost = new javax.swing.JButton();
        jComboBoxId = new javax.swing.JComboBox<>();
        jButtonLike = new javax.swing.JButton();
        jLabelMensajeRevision = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaSalidaRevision = new javax.swing.JTextArea();
        publicar = new javax.swing.JPanel();
        jLabelFecha = new javax.swing.JLabel();
        jTextFieldFecha = new javax.swing.JTextField();
        jLabelTema = new javax.swing.JLabel();
        jTextFieldTema = new javax.swing.JTextField();
        jLabelAlias = new javax.swing.JLabel();
        jTextFieldAlias = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelApellido = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        jLabelLinkedin = new javax.swing.JLabel();
        jTextFieldLinkedin = new javax.swing.JTextField();
        jLabelGithub = new javax.swing.JLabel();
        jTextFieldGithub = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabelDireccion = new javax.swing.JLabel();
        jTextFieldDireccion = new javax.swing.JTextField();
        jLabelTitulo = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jLabelTexto = new javax.swing.JLabel();
        jTextFieldTexto = new javax.swing.JTextField();
        jLabelMensajePublicacion = new javax.swing.JLabel();
        jButtonPublicar = new javax.swing.JButton();
        consultar = new javax.swing.JPanel();
        jLabelMensajeConsulta = new javax.swing.JLabel();
        jLabelConsulta = new javax.swing.JLabel();
        jRadioButtonUsuarios = new javax.swing.JRadioButton();
        jRadioButtonTemas = new javax.swing.JRadioButton();
        jRadioButtonPostPopular = new javax.swing.JRadioButton();
        jRadioButtonNumeroPosts = new javax.swing.JRadioButton();
        jButtonConsulta = new javax.swing.JButton();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jRadioButtonNumeroPostsUsuario = new javax.swing.JRadioButton();
        jRadioButtonDatosContacto = new javax.swing.JRadioButton();
        jRadioButtonRedesSociales = new javax.swing.JRadioButton();
        jRadioButtonTodosPostsUsuario = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaSalidaConsulta = new javax.swing.JTextArea();
        ajustesPersonales = new javax.swing.JPanel();
        jLabelCambios = new javax.swing.JLabel();
        jLabelMensajeAjustes = new javax.swing.JLabel();
        jRadioButtonAlias = new javax.swing.JRadioButton();
        jLabelAliasOld = new javax.swing.JLabel();
        jTextFieldAliasOld = new javax.swing.JTextField();
        jLabelAliasNew = new javax.swing.JLabel();
        jTextFieldAliasNew = new javax.swing.JTextField();
        jRadioButtonNombre = new javax.swing.JRadioButton();
        jLabelNombreOld = new javax.swing.JLabel();
        jTextFieldNombreOld = new javax.swing.JTextField();
        jLabelNombreNew = new javax.swing.JLabel();
        jTextFieldNombreNew = new javax.swing.JTextField();
        jRadioButtonApellido = new javax.swing.JRadioButton();
        jLabelApellidoOld = new javax.swing.JLabel();
        jTextFieldApellidoOld = new javax.swing.JTextField();
        jLabelApellidoNew = new javax.swing.JLabel();
        jTextFieldApellidoNew = new javax.swing.JTextField();
        jRadioButtonLinkedin = new javax.swing.JRadioButton();
        jLabelLinkedinOld = new javax.swing.JLabel();
        jTextFieldLinkedinOld = new javax.swing.JTextField();
        jLabelLinkedinNew = new javax.swing.JLabel();
        jTextFieldLinkedinNew = new javax.swing.JTextField();
        jRadioButtonGithub = new javax.swing.JRadioButton();
        jLabelGithubOld = new javax.swing.JLabel();
        jTextFieldGithubOld = new javax.swing.JTextField();
        jLabelGithubNew = new javax.swing.JLabel();
        jTextFieldGithubNew = new javax.swing.JTextField();
        jRadioButtonEmail = new javax.swing.JRadioButton();
        jLabelEmailOld = new javax.swing.JLabel();
        jTextFieldEmailOld = new javax.swing.JTextField();
        jLabelEmailNew = new javax.swing.JLabel();
        jTextFieldEmailNew = new javax.swing.JTextField();
        jRadioButtonTelefono = new javax.swing.JRadioButton();
        jLabelTelefonoOld = new javax.swing.JLabel();
        jTextFieldTelefonoOld = new javax.swing.JTextField();
        jLabelTelefonoNew = new javax.swing.JLabel();
        jTextFieldTelefonoNew = new javax.swing.JTextField();
        jRadioButtonDireccion = new javax.swing.JRadioButton();
        jLabelDireccionOld = new javax.swing.JLabel();
        jTextFieldDireccionOld = new javax.swing.JTextField();
        jLabelDireccionNew = new javax.swing.JLabel();
        jTextFieldDireccionNew = new javax.swing.JTextField();
        jButtonModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagenes/blog.png")).getImage()
        );
        setResizable(false);

        jButtonConectarSAX.setText("Conectar con base de datos");
        jButtonConectarSAX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConectarSAXActionPerformed(evt);
            }
        });

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(53, 60));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(936, 533));

        jButtonMostrarSAX.setText("Mostrar");
        jButtonMostrarSAX.setEnabled(false);
        jButtonMostrarSAX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarSAXActionPerformed(evt);
            }
        });

        jTextAreaSalidaSAX.setColumns(20);
        jTextAreaSalidaSAX.setRows(5);
        jScrollPane1.setViewportView(jTextAreaSalidaSAX);

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE)
                    .addGroup(homeLayout.createSequentialGroup()
                        .addComponent(jButtonMostrarSAX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelMensajeSAX, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonMostrarSAX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelMensajeSAX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Home", home);

        jButtonMostrarPost.setText("Mostrar Post");
        jButtonMostrarPost.setEnabled(false);
        jButtonMostrarPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarPostActionPerformed(evt);
            }
        });

        jComboBoxId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        jButtonLike.setText("Me gusta");
        jButtonLike.setEnabled(false);
        jButtonLike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLikeActionPerformed(evt);
            }
        });

        jTextAreaSalidaRevision.setColumns(20);
        jTextAreaSalidaRevision.setRows(5);
        jScrollPane2.setViewportView(jTextAreaSalidaRevision);

        javax.swing.GroupLayout revisarLayout = new javax.swing.GroupLayout(revisar);
        revisar.setLayout(revisarLayout);
        revisarLayout.setHorizontalGroup(
            revisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(revisarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(revisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(revisarLayout.createSequentialGroup()
                        .addComponent(jButtonMostrarPost)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLike)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelMensajeRevision, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE))
                .addContainerGap())
        );
        revisarLayout.setVerticalGroup(
            revisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(revisarLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(revisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(revisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonMostrarPost)
                        .addComponent(jComboBoxId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonLike))
                    .addComponent(jLabelMensajeRevision, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Revisar", revisar);

        jLabelFecha.setText("Fecha");

        jLabelTema.setText("Tema");

        jLabelAlias.setText("Alias");

        jLabelNombre.setText("Nombre");

        jLabelApellido.setText("Apellido");

        jLabelLinkedin.setText("Linkedin");

        jLabelGithub.setText("Github");

        jLabelEmail.setText("Email");

        jLabelTelefono.setText("Teléfono");

        jLabelDireccion.setText("Dirección");

        jLabelTitulo.setText("Título");

        jLabelTexto.setText("Texto");

        jButtonPublicar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonPublicar.setText("Publicar");
        jButtonPublicar.setEnabled(false);
        jButtonPublicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPublicarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout publicarLayout = new javax.swing.GroupLayout(publicar);
        publicar.setLayout(publicarLayout);
        publicarLayout.setHorizontalGroup(
            publicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(publicarLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(publicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(publicarLayout.createSequentialGroup()
                        .addComponent(jLabelAlias, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAlias, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(publicarLayout.createSequentialGroup()
                        .addGroup(publicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelLinkedin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(publicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(publicarLayout.createSequentialGroup()
                                .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelTema, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTema, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(publicarLayout.createSequentialGroup()
                                .addGroup(publicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(publicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(publicarLayout.createSequentialGroup()
                                        .addComponent(jLabelGithub, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldGithub, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(publicarLayout.createSequentialGroup()
                                        .addGroup(publicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButtonPublicar, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, publicarLayout.createSequentialGroup()
                                                .addComponent(jLabelTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(publicarLayout.createSequentialGroup()
                                        .addComponent(jLabelTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldTexto)))))))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, publicarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMensajePublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        publicarLayout.setVerticalGroup(
            publicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(publicarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMensajePublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(publicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFecha)
                    .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTema)
                    .addComponent(jTextFieldTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(publicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jLabelAlias)
                    .addComponent(jTextFieldAlias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelApellido)
                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(publicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLinkedin)
                    .addComponent(jTextFieldLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGithub)
                    .addComponent(jTextFieldGithub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(publicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTelefono)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDireccion)
                    .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(publicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitulo)
                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTexto)
                    .addComponent(jTextFieldTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jButtonPublicar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        jTabbedPane1.addTab("Publicar", publicar);

        jLabelConsulta.setText("Elige información a consultar:");

        buttonGroupConsulta.add(jRadioButtonUsuarios);
        jRadioButtonUsuarios.setText("Usuarios");

        buttonGroupConsulta.add(jRadioButtonTemas);
        jRadioButtonTemas.setText("Temas");

        buttonGroupConsulta.add(jRadioButtonPostPopular);
        jRadioButtonPostPopular.setText("Post más valorado");

        buttonGroupConsulta.add(jRadioButtonNumeroPosts);
        jRadioButtonNumeroPosts.setText("Número de posts");

        jButtonConsulta.setText("Realizar consulta");
        jButtonConsulta.setEnabled(false);
        jButtonConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaActionPerformed(evt);
            }
        });

        jLabelUsuario.setText("Usuario");

        buttonGroupConsulta.add(jRadioButtonNumeroPostsUsuario);
        jRadioButtonNumeroPostsUsuario.setText("Número de posts");

        buttonGroupConsulta.add(jRadioButtonDatosContacto);
        jRadioButtonDatosContacto.setText("Datos de contacto");

        buttonGroupConsulta.add(jRadioButtonRedesSociales);
        jRadioButtonRedesSociales.setText("Redes sociales");

        buttonGroupConsulta.add(jRadioButtonTodosPostsUsuario);
        jRadioButtonTodosPostsUsuario.setText("Todos sus posts");

        jTextAreaSalidaConsulta.setColumns(20);
        jTextAreaSalidaConsulta.setRows(5);
        jScrollPane3.setViewportView(jTextAreaSalidaConsulta);

        javax.swing.GroupLayout consultarLayout = new javax.swing.GroupLayout(consultar);
        consultar.setLayout(consultarLayout);
        consultarLayout.setHorizontalGroup(
            consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultarLayout.createSequentialGroup()
                .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(consultarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE))
                    .addGroup(consultarLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelConsulta)
                            .addGroup(consultarLayout.createSequentialGroup()
                                .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonUsuarios)
                                    .addComponent(jRadioButtonTemas))
                                .addGap(18, 18, 18)
                                .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonNumeroPosts)
                                    .addComponent(jRadioButtonPostPopular))))
                        .addGap(125, 125, 125)
                        .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(consultarLayout.createSequentialGroup()
                                .addComponent(jLabelUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelMensajeConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(consultarLayout.createSequentialGroup()
                                .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonNumeroPostsUsuario)
                                    .addComponent(jRadioButtonDatosContacto))
                                .addGap(18, 18, 18)
                                .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonTodosPostsUsuario)
                                    .addGroup(consultarLayout.createSequentialGroup()
                                        .addComponent(jRadioButtonRedesSociales)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap())
            .addGroup(consultarLayout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(jButtonConsulta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        consultarLayout.setVerticalGroup(
            consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMensajeConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(consultarLayout.createSequentialGroup()
                        .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelConsulta)
                            .addComponent(jLabelUsuario)
                            .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(consultarLayout.createSequentialGroup()
                                .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButtonRedesSociales)
                                    .addComponent(jRadioButtonNumeroPostsUsuario))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButtonDatosContacto)
                                    .addComponent(jRadioButtonTodosPostsUsuario)))
                            .addGroup(consultarLayout.createSequentialGroup()
                                .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButtonUsuarios)
                                    .addComponent(jRadioButtonPostPopular))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButtonTemas)
                                    .addComponent(jRadioButtonNumeroPosts))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jButtonConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consultar", consultar);

        jLabelCambios.setText("Realizar cambios en:");

        buttonGroupCambios.add(jRadioButtonAlias);
        jRadioButtonAlias.setText("Usuario");

        jLabelAliasOld.setText("Antiguo");

        jLabelAliasNew.setText("Nuevo");

        buttonGroupCambios.add(jRadioButtonNombre);
        jRadioButtonNombre.setText("Nombre");

        jLabelNombreOld.setText("Antiguo");

        jLabelNombreNew.setText("Nuevo");

        buttonGroupCambios.add(jRadioButtonApellido);
        jRadioButtonApellido.setText("Apellido");

        jLabelApellidoOld.setText("Antiguo");

        jLabelApellidoNew.setText("Nuevo");

        buttonGroupCambios.add(jRadioButtonLinkedin);
        jRadioButtonLinkedin.setText("Linkedin");

        jLabelLinkedinOld.setText("Antiguo");

        jLabelLinkedinNew.setText("Nuevo");

        buttonGroupCambios.add(jRadioButtonGithub);
        jRadioButtonGithub.setText("Github");

        jLabelGithubOld.setText("Antiguo");

        jLabelGithubNew.setText("Nuevo");

        buttonGroupCambios.add(jRadioButtonEmail);
        jRadioButtonEmail.setText("Email");

        jLabelEmailOld.setText("Antiguo");

        jLabelEmailNew.setText("Nuevo");

        buttonGroupCambios.add(jRadioButtonTelefono);
        jRadioButtonTelefono.setText("Teléfono");

        jLabelTelefonoOld.setText("Antiguo");

        jLabelTelefonoNew.setText("Nuevo");

        buttonGroupCambios.add(jRadioButtonDireccion);
        jRadioButtonDireccion.setText("Dirección");

        jLabelDireccionOld.setText("Antiguo");

        jLabelDireccionNew.setText("Nuevo");

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ajustesPersonalesLayout = new javax.swing.GroupLayout(ajustesPersonales);
        ajustesPersonales.setLayout(ajustesPersonalesLayout);
        ajustesPersonalesLayout.setHorizontalGroup(
            ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajustesPersonalesLayout.createSequentialGroup()
                .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ajustesPersonalesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelCambios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelMensajeAjustes, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ajustesPersonalesLayout.createSequentialGroup()
                        .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ajustesPersonalesLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelAliasOld, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelAliasNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldAliasNew)
                                    .addComponent(jTextFieldAliasOld, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ajustesPersonalesLayout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonLinkedin)
                                    .addComponent(jRadioButtonAlias))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ajustesPersonalesLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ajustesPersonalesLayout.createSequentialGroup()
                                        .addComponent(jRadioButtonNombre)
                                        .addGap(10, 10, 10))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ajustesPersonalesLayout.createSequentialGroup()
                                        .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabelNombreOld, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelNombreNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)))
                                .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldNombreOld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                    .addComponent(jTextFieldNombreNew, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ajustesPersonalesLayout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jRadioButtonApellido))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ajustesPersonalesLayout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ajustesPersonalesLayout.createSequentialGroup()
                                                .addComponent(jLabelApellidoNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextFieldApellidoNew, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ajustesPersonalesLayout.createSequentialGroup()
                                                .addComponent(jLabelApellidoOld)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextFieldApellidoOld, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(ajustesPersonalesLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRadioButtonGithub)
                                    .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabelGithubNew, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelGithubOld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ajustesPersonalesLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ajustesPersonalesLayout.createSequentialGroup()
                                .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ajustesPersonalesLayout.createSequentialGroup()
                                        .addComponent(jRadioButtonEmail)
                                        .addGap(192, 192, 192))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ajustesPersonalesLayout.createSequentialGroup()
                                        .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabelLinkedinOld, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelLinkedinNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldLinkedinOld)
                                            .addComponent(jTextFieldLinkedinNew, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))))
                                .addGap(18, 18, 18)
                                .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(ajustesPersonalesLayout.createSequentialGroup()
                                        .addComponent(jRadioButtonTelefono)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldGithubOld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                            .addComponent(jTextFieldGithubNew, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(24, 24, 24)
                                        .addComponent(jRadioButtonDireccion))))
                            .addGroup(ajustesPersonalesLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ajustesPersonalesLayout.createSequentialGroup()
                                        .addComponent(jLabelEmailOld)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldEmailOld, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ajustesPersonalesLayout.createSequentialGroup()
                                        .addComponent(jLabelEmailNew, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldEmailNew)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelTelefonoOld, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelTelefonoNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldTelefonoNew, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldTelefonoOld, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(ajustesPersonalesLayout.createSequentialGroup()
                                        .addComponent(jLabelDireccionNew, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldDireccionNew, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ajustesPersonalesLayout.createSequentialGroup()
                                        .addComponent(jLabelDireccionOld)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldDireccionOld, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        ajustesPersonalesLayout.setVerticalGroup(
            ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajustesPersonalesLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCambios)
                    .addComponent(jLabelMensajeAjustes, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ajustesPersonalesLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonAlias)
                            .addComponent(jRadioButtonNombre)))
                    .addGroup(ajustesPersonalesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonApellido)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ajustesPersonalesLayout.createSequentialGroup()
                        .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldAliasOld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAliasOld))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldAliasNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAliasNew)))
                    .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(ajustesPersonalesLayout.createSequentialGroup()
                            .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldNombreOld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelNombreOld))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldNombreNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelNombreNew)))
                        .addGroup(ajustesPersonalesLayout.createSequentialGroup()
                            .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldApellidoOld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelApellidoOld))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldApellidoNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelApellidoNew)))))
                .addGap(29, 29, 29)
                .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonLinkedin)
                    .addComponent(jRadioButtonGithub))
                .addGap(3, 3, 3)
                .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ajustesPersonalesLayout.createSequentialGroup()
                        .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldLinkedinOld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelLinkedinOld))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldLinkedinNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelLinkedinNew))
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonEmail))
                    .addGroup(ajustesPersonalesLayout.createSequentialGroup()
                        .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldGithubOld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelGithubOld))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldGithubNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelGithubNew))
                        .addGap(18, 18, 18)
                        .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonDireccion)
                            .addComponent(jRadioButtonTelefono))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ajustesPersonalesLayout.createSequentialGroup()
                        .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEmailOld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEmailOld))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEmailNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEmailNew)))
                    .addGroup(ajustesPersonalesLayout.createSequentialGroup()
                        .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDireccionOld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDireccionOld))
                        .addGap(4, 4, 4)
                        .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDireccionNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDireccionNew)))
                    .addGroup(ajustesPersonalesLayout.createSequentialGroup()
                        .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTelefonoOld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTelefonoOld))
                        .addGap(3, 3, 3)
                        .addGroup(ajustesPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTelefonoNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTelefonoNew))))
                .addGap(31, 31, 31)
                .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ajustes personales", ajustesPersonales);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 936, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(394, 394, 394)
                        .addComponent(jButtonConectarSAX)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelMensajeConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonConectarSAX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelMensajeConexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConectarSAXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConectarSAXActionPerformed

        //Abre el fichero, habilita los botones y actualiza el combobox para que se pueda elegir un post por su id
        
        ficheroXML = dialogoSeleccionarFichero();
        if (ficheroXML == null) {
            this.jLabelMensajeConexion.setText("Error en conexión con base de datos.");
            this.jButtonMostrarSAX.setEnabled(false);
            this.jButtonMostrarPost.setEnabled(false);
            this.jButtonLike.setEnabled(false);
            this.jButtonPublicar.setEnabled(false);
            this.jButtonConsulta.setEnabled(false);
            this.jButtonModificar.setEnabled(false);
        } else {
            this.jLabelMensajeConexion.setText("¡Conexión establecida correctamente!");
            this.jButtonMostrarSAX.setEnabled(true);
            this.jButtonMostrarPost.setEnabled(true);
            this.jButtonLike.setEnabled(true);
            this.jButtonPublicar.setEnabled(true);
            this.jButtonConsulta.setEnabled(true);
            this.jButtonModificar.setEnabled(true);
            actualizarComboboxItems();            
        }


    }//GEN-LAST:event_jButtonConectarSAXActionPerformed

    private void jButtonMostrarSAXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarSAXActionPerformed

        //Muestra el contenido del archivo XML con SAX (primero prepara el SAX por si se ha cambiado algo)
        
        if (gesSAX.preparar_SAX(ficheroXML) == -1) {
            this.jLabelMensajeSAX.setText("Error en acceso a datos.");
        } else {
            this.jTextAreaSalidaSAX.setText(gesSAX.recorrerSAX());
        }

    }//GEN-LAST:event_jButtonMostrarSAXActionPerformed

    private void jButtonMostrarPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarPostActionPerformed

        //Muestra el resultado de la consulta del post seleccionado en el combobox
        
        if (gesXPath.preparar_XPath(ficheroXML) == -1) {
            this.jLabelMensajeRevision.setText("Error en acceso a datos.");
        } else {
            String consultaPost = "/Blog/Post[./@id='" + String.valueOf(jComboBoxId.getSelectedItem()) + "']";
            this.jTextAreaSalidaRevision.setText(gesXPath.consultar_post(consultaPost));
        }

    }//GEN-LAST:event_jButtonMostrarPostActionPerformed

    private void jButtonLikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLikeActionPerformed

        //Añade un like al post seleccionado en el combobox
        
        if (gesJAXB.preparar_JAXB(ficheroXML) == -1) {
            this.jLabelMensajeRevision.setText("Error en acceso a datos.");
        } else {
            if (gesJAXB.annadirLike(String.valueOf(jComboBoxId.getSelectedItem()), ficheroXML) == -1) {
                this.jLabelMensajeRevision.setText("Error en dar like.");
            } else {
                this.jLabelMensajeRevision.setText("¡Me gusta!");
            }
        }

    }//GEN-LAST:event_jButtonLikeActionPerformed

    private void jButtonPublicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPublicarActionPerformed

        //Añade un elemento Post en el archivo XML y actualiza el combobox
        
        if (gesDOM.preparar_DOM(ficheroXML) == -1) {
            this.jLabelMensajePublicacion.setText("Error en acceso a datos.");
        } else {
            
            String campos[] = { this.jTextFieldFecha.getText(), this.jTextFieldTema.getText(),
                                this.jTextFieldAlias.getText(), this.jTextFieldNombre.getText(), this.jTextFieldApellido.getText(),
                                this.jTextFieldLinkedin.getText(), this.jTextFieldGithub.getText(),
                                this.jTextFieldEmail.getText(), this.jTextFieldTelefono.getText(), this.jTextFieldDireccion.getText(),
                                this.jTextFieldTitulo.getText(), this.jTextFieldTexto.getText() };

            
            if(gesDOM.publicarPost(campos, ficheroXML) == -1){
                this.jLabelMensajePublicacion.setText("Error al publicar el post.");
            } else {
                actualizarComboboxItems();
            }
        }
        
    }//GEN-LAST:event_jButtonPublicarActionPerformed

    private void jButtonConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaActionPerformed
        
        //Realiza la consulta seleccionada con el radio button y la muestra en el text area
        
        if (gesXPath.preparar_XPath(ficheroXML) == -1) {
            this.jLabelMensajeConsulta.setText("Error en acceso a datos.");
        } else {
            if(jRadioButtonUsuarios.isSelected()){
                String consultaPost = "//@alias";
                this.jTextAreaSalidaConsulta.setText(gesXPath.consultar_atributos(consultaPost));
            } else if(jRadioButtonTemas.isSelected()){
                String consultaPost = "//@tema";
                this.jTextAreaSalidaConsulta.setText(gesXPath.consultar_atributos(consultaPost));
            } else if(jRadioButtonPostPopular.isSelected()){
                String id = String.valueOf(gesXPath.buscar_post_mas_popular());
                String consultaPost = "/Blog/Post[./@id='" + id  + "']";
                this.jTextAreaSalidaConsulta.setText(gesXPath.consultar_post(consultaPost));
            } else if(jRadioButtonNumeroPosts.isSelected()){
                String consultaPost = "//Post";
                this.jTextAreaSalidaConsulta.setText(gesXPath.consultar_numero_posts(consultaPost));
            } else if(jRadioButtonNumeroPostsUsuario.isSelected()){
                String consultaPost = "//Post";
                this.jTextAreaSalidaConsulta.setText(gesXPath.consultar_numero_posts(consultaPost, jTextFieldUsuario.getText()));
            } else if(jRadioButtonDatosContacto.isSelected()){
                String consultaPost = "//Usuario[./@alias='" + jTextFieldUsuario.getText() + "']";
                this.jTextAreaSalidaConsulta.setText(gesXPath.consultar_informacion_usuario(consultaPost, "DatosContacto"));
            } else if(jRadioButtonRedesSociales.isSelected()){
                String consultaPost = "//Usuario[./@alias='" + jTextFieldUsuario.getText() + "']";
                this.jTextAreaSalidaConsulta.setText(gesXPath.consultar_informacion_usuario(consultaPost, "RedesSociales"));
            } else if(jRadioButtonTodosPostsUsuario.isSelected()){
                String consultaPost = "//Post[./Usuario/@alias='" + jTextFieldUsuario.getText() + "']";
                this.jTextAreaSalidaConsulta.setText(gesXPath.consultar_todos_posts(consultaPost));
            }
        }
        
    }//GEN-LAST:event_jButtonConsultaActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        
        //Permite modificar un elemento con el texto antiguo y el nuevo
        
        if (gesJAXB.preparar_JAXB(ficheroXML) == -1) {
            this.jLabelMensajeAjustes.setText("Error en acceso a datos.");
        } else {
            if(this.jRadioButtonAlias.isSelected()){
                if (gesJAXB.modificar_JAXB("Alias", this.jTextFieldAliasOld.getText(), this.jTextFieldAliasNew.getText(),  ficheroXML) == -1) {
                    this.jLabelMensajeAjustes.setText("Error la modificación.");
                } else {
                    this.jLabelMensajeAjustes.setText("¡Elemento modificado!");
                }
            }else if(this.jRadioButtonNombre.isSelected()){
                if (gesJAXB.modificar_JAXB("Nombre", this.jTextFieldNombreOld.getText(), this.jTextFieldNombreNew.getText(),  ficheroXML) == -1) {
                    this.jLabelMensajeAjustes.setText("Error la modificación.");
                } else {
                    this.jLabelMensajeAjustes.setText("¡Elemento modificado!");
                }
            } else if(this.jRadioButtonApellido.isSelected()){
                if (gesJAXB.modificar_JAXB("Apellido", this.jTextFieldApellidoOld.getText(), this.jTextFieldApellidoNew.getText(),  ficheroXML) == -1) {
                    this.jLabelMensajeAjustes.setText("Error la modificación.");
                } else {
                    this.jLabelMensajeAjustes.setText("¡Elemento modificado!");
                }
            } else if(this.jRadioButtonLinkedin.isSelected()){
                if (gesJAXB.modificar_JAXB("Linkedin", this.jTextFieldLinkedinOld.getText(), this.jTextFieldLinkedinNew.getText(),  ficheroXML) == -1) {
                    this.jLabelMensajeAjustes.setText("Error la modificación.");
                } else {
                    this.jLabelMensajeAjustes.setText("¡Elemento modificado!");
                }
            } else if(this.jRadioButtonGithub.isSelected()){
                if (gesJAXB.modificar_JAXB("Github", this.jTextFieldGithubOld.getText(), this.jTextFieldGithubNew.getText(),  ficheroXML) == -1) {
                    this.jLabelMensajeAjustes.setText("Error la modificación.");
                } else {
                    this.jLabelMensajeAjustes.setText("¡Elemento modificado!");
                }
            } else if(this.jRadioButtonEmail.isSelected()){
                if (gesJAXB.modificar_JAXB("Email", this.jTextFieldEmailOld.getText(), this.jTextFieldEmailNew.getText(),  ficheroXML) == -1) {
                    this.jLabelMensajeAjustes.setText("Error la modificación.");
                } else {
                    this.jLabelMensajeAjustes.setText("¡Elemento modificado!");
                }
            } else if(this.jRadioButtonTelefono.isSelected()){
                if (gesJAXB.modificar_JAXB("Telefono", this.jTextFieldTelefonoOld.getText(), this.jTextFieldTelefonoNew.getText(),  ficheroXML) == -1) {
                    this.jLabelMensajeAjustes.setText("Error la modificación.");
                } else {
                    this.jLabelMensajeAjustes.setText("¡Elemento modificado!");
                }
            } else if(this.jRadioButtonDireccion.isSelected()){
                if (gesJAXB.modificar_JAXB("Direccion", this.jTextFieldDireccionOld.getText(), this.jTextFieldDireccionNew.getText(),  ficheroXML) == -1) {
                    this.jLabelMensajeAjustes.setText("Error la modificación.");
                } else {
                    this.jLabelMensajeAjustes.setText("¡Elemento modificado!");
                }
            } 
        }
        
    }//GEN-LAST:event_jButtonModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ajustesPersonales;
    private javax.swing.ButtonGroup buttonGroupCambios;
    private javax.swing.ButtonGroup buttonGroupConsulta;
    private javax.swing.JPanel consultar;
    private javax.swing.JPanel home;
    private javax.swing.JButton jButtonConectarSAX;
    private javax.swing.JButton jButtonConsulta;
    private javax.swing.JButton jButtonLike;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonMostrarPost;
    private javax.swing.JButton jButtonMostrarSAX;
    private javax.swing.JButton jButtonPublicar;
    private javax.swing.JComboBox<String> jComboBoxId;
    private javax.swing.JLabel jLabelAlias;
    private javax.swing.JLabel jLabelAliasNew;
    private javax.swing.JLabel jLabelAliasOld;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelApellidoNew;
    private javax.swing.JLabel jLabelApellidoOld;
    private javax.swing.JLabel jLabelCambios;
    private javax.swing.JLabel jLabelConsulta;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelDireccionNew;
    private javax.swing.JLabel jLabelDireccionOld;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEmailNew;
    private javax.swing.JLabel jLabelEmailOld;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelGithub;
    private javax.swing.JLabel jLabelGithubNew;
    private javax.swing.JLabel jLabelGithubOld;
    private javax.swing.JLabel jLabelLinkedin;
    private javax.swing.JLabel jLabelLinkedinNew;
    private javax.swing.JLabel jLabelLinkedinOld;
    private javax.swing.JLabel jLabelMensajeAjustes;
    private javax.swing.JLabel jLabelMensajeConexion;
    private javax.swing.JLabel jLabelMensajeConsulta;
    private javax.swing.JLabel jLabelMensajePublicacion;
    private javax.swing.JLabel jLabelMensajeRevision;
    private javax.swing.JLabel jLabelMensajeSAX;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombreNew;
    private javax.swing.JLabel jLabelNombreOld;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTelefonoNew;
    private javax.swing.JLabel jLabelTelefonoOld;
    private javax.swing.JLabel jLabelTema;
    private javax.swing.JLabel jLabelTexto;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JRadioButton jRadioButtonAlias;
    private javax.swing.JRadioButton jRadioButtonApellido;
    private javax.swing.JRadioButton jRadioButtonDatosContacto;
    private javax.swing.JRadioButton jRadioButtonDireccion;
    private javax.swing.JRadioButton jRadioButtonEmail;
    private javax.swing.JRadioButton jRadioButtonGithub;
    private javax.swing.JRadioButton jRadioButtonLinkedin;
    private javax.swing.JRadioButton jRadioButtonNombre;
    private javax.swing.JRadioButton jRadioButtonNumeroPosts;
    private javax.swing.JRadioButton jRadioButtonNumeroPostsUsuario;
    private javax.swing.JRadioButton jRadioButtonPostPopular;
    private javax.swing.JRadioButton jRadioButtonRedesSociales;
    private javax.swing.JRadioButton jRadioButtonTelefono;
    private javax.swing.JRadioButton jRadioButtonTemas;
    private javax.swing.JRadioButton jRadioButtonTodosPostsUsuario;
    private javax.swing.JRadioButton jRadioButtonUsuarios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextAreaSalidaConsulta;
    private javax.swing.JTextArea jTextAreaSalidaRevision;
    private javax.swing.JTextArea jTextAreaSalidaSAX;
    private javax.swing.JTextField jTextFieldAlias;
    private javax.swing.JTextField jTextFieldAliasNew;
    private javax.swing.JTextField jTextFieldAliasOld;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldApellidoNew;
    private javax.swing.JTextField jTextFieldApellidoOld;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldDireccionNew;
    private javax.swing.JTextField jTextFieldDireccionOld;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEmailNew;
    private javax.swing.JTextField jTextFieldEmailOld;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldGithub;
    private javax.swing.JTextField jTextFieldGithubNew;
    private javax.swing.JTextField jTextFieldGithubOld;
    private javax.swing.JTextField jTextFieldLinkedin;
    private javax.swing.JTextField jTextFieldLinkedinNew;
    private javax.swing.JTextField jTextFieldLinkedinOld;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNombreNew;
    private javax.swing.JTextField jTextFieldNombreOld;
    private javax.swing.JTextField jTextFieldTelefono;
    private javax.swing.JTextField jTextFieldTelefonoNew;
    private javax.swing.JTextField jTextFieldTelefonoOld;
    private javax.swing.JTextField jTextFieldTema;
    private javax.swing.JTextField jTextFieldTexto;
    private javax.swing.JTextField jTextFieldTitulo;
    private javax.swing.JTextField jTextFieldUsuario;
    private javax.swing.JPanel publicar;
    private javax.swing.JPanel revisar;
    // End of variables declaration//GEN-END:variables
    /**
     * @see Abre el fichero seleccionado.
     * @return Fichero seleccionado.
     */
    private File dialogoSeleccionarFichero() {

        File fichero = null;

        try {
            JFileChooser fco = new JFileChooser();

            //Busca evitar abrir ficheros binarios
            fco.setFileFilter(new FileNameExtensionFilter("Archivos xml", "xml"));

            fco.setMultiSelectionEnabled(false);
            fco.setDialogType(JFileChooser.OPEN_DIALOG);

            //Si no se produce ningún error seleccion será 0
            int seleccion = fco.showOpenDialog(this);
            if (seleccion == JFileChooser.APPROVE_OPTION) {
                fichero = fco.getSelectedFile();
                String nombre = fichero.getName();
                String extension = nombre.substring(nombre.lastIndexOf('.') + 1, nombre.length());

                if (!extension.equalsIgnoreCase("xml")) {

                    JOptionPane.showConfirmDialog(null, "Estensión seleccionada no válida.", "", JOptionPane.PLAIN_MESSAGE);

                } else {
                    return fichero;
                }
            }
        } catch (Exception ex) {
            System.out.println("Fichero no seleccionado.");
        }

        return null;
    }
    /**
     * @see Actualiza jComboBoxId para que tenga el mismo número de elementos que el número de posts en el blog.
     */
    private void actualizarComboboxItems() {
        
        if (gesDOM.preparar_DOM(ficheroXML) == -1) {
                this.jLabelMensajeConexion.setText("Error en conexión con base de datos.");
            } else {
                this.jComboBoxId.removeAllItems();
                int numeroPosts = gesDOM.contarPosts();
                for (int i = 1; i <= numeroPosts; i++) {
                    this.jComboBoxId.addItem(String.valueOf(i));
                }
            }
    }
}
